version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.11.1
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Running tests
          command: npm test
  deploy:
    docker:
      - image: circleci/node:chakracore-8.11.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:f6:e0:95:2b:52:38:03:77:80:f7:36:65:f0:fe:82"
      - run:
          name: AWS EC2 deploy
          command: |
            ssh -o StrictHostKeyChecking=no -p 22 ec2-user@3.82.92.234 \
            "echo Start deploy && \
            cp ./tmp/keyfile.pem /home/ec2-user/sample
            echo Deploy end"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
